# Generated by Django 3.0.2 on 2020-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(max_length=200)),
                ('text_2', models.CharField(max_length=200)),
            ],
        ),
    ]
